# Generated by Django 6.0 on 2025-12-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0003_creation_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creation',
            name='colors',
        ),
    ]
