# Generated by Django 6.0 on 2025-12-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_image', '0002_alter_galleryimage_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
