# Generated by Django 6.0 on 2025-12-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='creations/images/'),
        ),
    ]
