# Generated by Django 6.0 on 2025-12-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
        ('creations', '0002_creation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='creations', to='color.color'),
        ),
    ]
