# Generated by Django 6.0 on 2025-12-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_combo', '0001_initial'),
        ('creations', '0005_creation_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='color_combos',
            field=models.ManyToManyField(blank=True, related_name='creations', to='color_combo.colorcombo'),
        ),
    ]
