# Generated by Django 6.0 on 2025-12-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0006_creation_color_combos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creation',
            name='image',
        ),
    ]
