# Generated by Django 6.0 on 2025-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0007_remove_creation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creation',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='creation',
            name='mini_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
