# Generated by Django 6.0 on 2025-12-23 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ColorComboColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.color')),
                ('color_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color_combo.colorcombo')),
            ],
            options={
                'unique_together': {('color_combo', 'color')},
            },
        ),
        migrations.AddField(
            model_name='colorcombo',
            name='colors',
            field=models.ManyToManyField(related_name='color_combos', through='color_combo.ColorComboColor', to='color.color'),
        ),
    ]
